#!/bin/bash

source ./scripts/utils/constant/gum_options_strings.sh

PKG_AppIcon=(
    "flutter_launcher_icons"
)
PKG_SplashScreen=(
    "flutter_native_splash"
)
PKG_OnBoarding=(
    "introduction_screen"
)
PKG_Animations=(
    "lottie"
    "animate_do"
    "flutter_animate"
    "animated_text_kit"
    "animations"
)
PKG_Indicators=(
    "flutter_slidable"
    "infinite_scroll_pagination"
    "smooth_page_indicator"
    "liquid_pull_to_refresh"
    "action_slider"
    "scroll_to_hide"
)
PKG_BottomNavBar=(
    "google_nav_bar"
    "animated_bottom_navigation_bar"
    "persistent_bottom_nav_bar"
    "persistent_bottom_nav_bar_v2"
    "floating_bottom_navigation_bar"
)
PKG_StateManagement=(
    "bloc"
    "flutter_bloc"
    "hydrated_bloc"
    "provider"
    "equatable"
    "riverpod"
    "flutter_riverpod"
)
PKG_Navigation=(
    "go_router"
)
PKG_Networking=(
    "http"
    "dio"
    "pretty_dio_logger"
    "json_serializable"
    "json_annotation"
    "freezed"
    "freezed_annotation"
    "retrofit"
    "retrofit_generator"
    "cached_network_image"
    "connectivity_plus"
    "internet_connection_checker"
    "internet_connection_checker_plus"
    "build_runner"
)
PKG_DependencyInjection=(
    "get_it"
)
PKG_Storage=(
    "shared_preferences"
    "hive"
    "hive_flutter"
    "hive_generator"
    "sqflite"
    "graphql_flutter"
)
PKG_Cloud=(
    "firebase_core"
    "firebase_auth"
    "cloud_firestore"
    "firebase_analytics"
    "firebase_crashlytics"
    "firebase_messaging"
    "supabase"
    "supabase_flutter"
)
PKG_Auth=(
    "google_sign_in"
    "sign_in_with_apple"
    "googleapis_auth"
    "flutter_facebook_auth"
)
PKG_Biometric=(
    "local_auth"
    "flutter_screen_lock"
    "biometric_signature"
    "passkeys"
)
PKG_Localization=(
    "easy_localization"
    "intl"
    "flutter_localization"
)
PKG_Notifications=(
    "flutter_local_notifications"
    "awesome_notifications"
    "flutter_local_notifications_platform_interface"
)
PKG_Responsive=(
    "flutter_screenutil"
    "responsive_framework"
    "auto_size_text"
)
PKG_UI_Utils=(
    "flutter_spinkit"
    "shimmer"
    "shimmer_animation"
    "skeletonizer"
    "vibration"
    "haptic_feedback"
    "image_picker"
    "audioplayers"
    "video_player"
    "toastification"
    "delightful_toast"
    "cherry_toast"
    "showcaseview"
    "tutorial_coach_mark"
    "restart_app"
)
PKG_Others=(
    "flutter_svg"
    "url_launcher"
    "path_provider"
    "share_plus"
    "package_info_plus"
    "device_info_plus"
)
